# Generated by Django 4.1.5 on 2023-02-01 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_sharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('earliest_arrival_time', models.DateTimeField()),
                ('latest_arrival_time', models.DateTimeField()),
                ('num_passengers', models.PositiveIntegerField(default=1)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('num_passengers', models.PositiveIntegerField(default=4)),
                ('vechicle_type', models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('--', '--')], default='--', max_length=20)),
                ('sharing', models.BooleanField()),
                ('special_requests', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('open', 'open'), ('confirmed', 'confirmed'), ('completed', 'completed')], default='open', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ManyToManyField(blank=True, related_name='sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
