# Generated by Django 4.1.5 on 2023-02-02 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_owner',
            name='vechicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('VAN', 'VAN')], default='--', max_length=20),
        ),
        migrations.CreateModel(
            name='Ride_driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, default='', max_length=10)),
                ('num_passengers', models.PositiveIntegerField(default=1)),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('--', '--')], default='SEDAN', max_length=20)),
                ('special_info', models.TextField(blank=True, default='')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
