# Generated by Django 4.1.5 on 2023-02-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_alter_ride_owner_vechicle_type_ride_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_owner',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ride_owner',
            name='license_plate',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
