# Generated by Django 4.1.5 on 2023-02-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_ride_owner_driver_name_ride_owner_license_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride_owner',
            name='vechicle_type',
        ),
        migrations.AddField(
            model_name='ride_owner',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('--', '--')], default='--', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride_driver',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('VAN', 'VAN')], default='SEDAN', max_length=20),
        ),
    ]
