# Generated by Django 4.1.5 on 2023-02-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_remove_ride_owner_vechicle_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride_owner',
            name='sharer',
        ),
        migrations.AddField(
            model_name='ride_owner',
            name='sharer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
